# 설정
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-hexagonal-deployment
  namespace: default
  labels:
    app: service-hexagonal
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: service-hexagonal
  template:
    metadata:
      labels:
        app: service-hexagonal
    spec:
      containers:
        - name: service-hexagonal
          image: 192.168.75.144:9001/docker-hosted/hexagonal:latest
          command: [ "java" ]
          args: [ "-Djava.security.egd=file:/dev/./urandom", "-jar","/app.jar" ]
          imagePullPolicy: Always
          ports:
            - containerPort: 8030
