version: '3'
services:
  nexus:
    image: sonatype/nexus3:latest  # 또는 원하는 NEXUS 이미지 및 버전을 지정
    container_name: nexus
    ports: # 호스트 포트와 컨테이너 포트를 매핑합니다. 필요에 따라 변경 가능
      - "8081:8081"
      - "9001:9001"
    volumes:
      - ~/data/nexus:/nexus-data # -v 옵션 (다렉토리 마운트 설정)
      - nexus_data:/nexus
    environment:
      - SONATYPE_WORK=/nexus-data/work
      - SONATYPE_TEMP=/nexus-data/tmp
    networks:
      - nexus_network

volumes:
  nexus_data:

networks:
  nexus_network: